INFO 2020-04-14 00:50:21,601 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-14 00:50:21,627 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-14 00:50:21,648 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-14 00:50:21,648 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
INFO 2020-04-14 00:50:21,661 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
WARNING 2020-04-14 00:50:21,996 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
ERROR 2020-04-14 00:50:28,494 exception 135 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django_redis/cache.py", line 124, in has_key
    return self.client.has_key(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django_redis/client/default.py", line 474, in has_key
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/users/views.py", line 116, in post
    login(request, user)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 140, in login
    request.session.cycle_key()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 311, in cycle_key
    self.create()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/sessions/backends/cache.py", line 44, in create
    self._session_key = self._get_new_session_key()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 164, in _get_new_session_key
    if not self.exists(session_key):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/sessions/backends/cache.py", line 71, in exists
    return session_key and (self.cache_key_prefix + session_key) in self._cache
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/cache/backends/base.py", line 203, in __contains__
    return self.has_key(key)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django_redis/client/default.py", line 472, in has_key
    return client.exists(key) == 1
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/redis/client.py", line 1554, in exists
    return self.execute_command('EXISTS', *names)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
ERROR 2020-04-14 00:50:28,822 basehttp 124 "POST /login/?next=/ HTTP/1.1" 500 150654
INFO 2020-04-14 00:51:32,664 basehttp 124 "POST /login/?next=/ HTTP/1.1" 302 0
ERROR 2020-04-14 00:51:32,735 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 77, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'goods'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 38, in get
    return render(request, "index.html", context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/backends/jinja2.py", line 81, in render
    return self.template.render(context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/templates/index.html", line 58, in top-level template code
    <a href="{{ url('goods:list', args=(category_id, page_num)) }}?sort=default" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 87, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'goods' is not a registered namespace
ERROR 2020-04-14 00:51:32,995 basehttp 124 "GET / HTTP/1.1" 500 143812
INFO 2020-04-14 00:56:56,611 basehttp 124 "GET / HTTP/1.1" 200 2901
INFO 2020-04-14 00:56:56,643 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-14 00:56:56,649 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
INFO 2020-04-14 00:56:56,652 basehttp 124 "GET /static/js/jquery.pagination.min.js HTTP/1.1" 200 2935
INFO 2020-04-14 00:57:02,520 basehttp 124 "GET / HTTP/1.1" 200 2901
INFO 2020-04-14 00:57:03,231 basehttp 124 "GET / HTTP/1.1" 200 2901
INFO 2020-04-14 00:57:03,743 basehttp 124 "GET / HTTP/1.1" 200 2901
INFO 2020-04-14 00:57:05,575 basehttp 124 "GET /logout/ HTTP/1.1" 302 0
INFO 2020-04-14 00:57:05,580 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-14 00:57:05,603 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-14 00:57:05,632 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
WARNING 2020-04-14 00:57:05,649 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-14 00:57:10,924 basehttp 124 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2020-04-14 00:57:10,948 basehttp 124 "GET / HTTP/1.1" 200 2901
INFO 2020-04-14 00:57:31,236 basehttp 124 "GET / HTTP/1.1" 200 2901
ERROR 2020-04-14 01:07:50,213 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 01:07:50,365 basehttp 124 "GET / HTTP/1.1" 500 86210
ERROR 2020-04-14 01:12:23,268 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 01:12:23,421 basehttp 124 "GET / HTTP/1.1" 500 86210
ERROR 2020-04-14 01:13:33,299 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 01:13:33,432 basehttp 124 "GET / HTTP/1.1" 500 86210
ERROR 2020-04-14 01:13:34,326 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 01:13:34,458 basehttp 124 "GET / HTTP/1.1" 500 86211
ERROR 2020-04-14 01:13:35,293 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 01:13:35,425 basehttp 124 "GET / HTTP/1.1" 500 86210
ERROR 2020-04-14 12:13:27,730 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 12:13:27,882 basehttp 124 "GET / HTTP/1.1" 500 86049
WARNING 2020-04-14 12:35:11,197 csrf 160 Forbidden (CSRF token missing or incorrect.): /incre/
WARNING 2020-04-14 12:35:11,203 basehttp 124 "POST /incre/ HTTP/1.1" 403 2502
ERROR 2020-04-14 12:35:17,470 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'page_num'
ERROR 2020-04-14 12:35:17,608 basehttp 124 "GET / HTTP/1.1" 500 85753
WARNING 2020-04-14 12:38:19,353 base 152 Not Found: /
WARNING 2020-04-14 12:38:19,355 basehttp 124 "GET / HTTP/1.1" 404 3545
INFO 2020-04-14 12:38:27,207 basehttp 124 "GET /1 HTTP/1.1" 301 0
ERROR 2020-04-14 12:38:27,229 exception 135 Internal Server Error: /1/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 27, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-14 12:38:27,389 basehttp 124 "GET /1/ HTTP/1.1" 500 98594
ERROR 2020-04-14 12:38:41,311 exception 135 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/users/views.py", line 89, in get
    return render(request, 'login.html')
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/backends/jinja2.py", line 81, in render
    return self.template.render(context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/templates/login.html", line 13, in top-level template code
    <a href={{ url("contents:index") }} class="login_logo"><img src="{{ static('images/logo.jpg') }}" width="100px" height="100px"></a>
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' with no arguments not found. 1 pattern(s) tried: ['(?P<page_num>\\d+)/$']
ERROR 2020-04-14 12:38:41,511 basehttp 124 "GET /login/ HTTP/1.1" 500 135497
ERROR 2020-04-14 12:39:00,210 exception 135 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/users/views.py", line 35, in get
    return render(request, 'register.html')
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/backends/jinja2.py", line 81, in render
    return self.template.render(context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/templates/register.html", line 15, in top-level template code
    <a href={{ url("contents:index") }} class="reg_logo"><img src={{ static("images/logo.jpg") }}
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' with no arguments not found. 1 pattern(s) tried: ['(?P<page_num>\\d+)/$']
ERROR 2020-04-14 12:39:00,428 basehttp 124 "GET /register/ HTTP/1.1" 500 135187
ERROR 2020-04-14 12:41:03,830 exception 135 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/users/views.py", line 35, in get
    return render(request, 'register.html')
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/backends/jinja2.py", line 81, in render
    return self.template.render(context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/templates/register.html", line 15, in top-level template code
    <a href={{ url("contents:index") }} class="reg_logo"><img src={{ static("images/logo.jpg") }}
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' with no arguments not found. 1 pattern(s) tried: ['(?P<page_num>\\d+)/$']
ERROR 2020-04-14 12:41:04,082 basehttp 124 "GET /register/ HTTP/1.1" 500 135322
ERROR 2020-04-14 12:41:43,223 exception 135 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/users/views.py", line 89, in get
    return render(request, 'login.html')
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/backends/jinja2.py", line 81, in render
    return self.template.render(context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/templates/login.html", line 13, in top-level template code
    <a href={{ url("contents:index") }} class="login_logo"><img src="{{ static('images/logo.jpg') }}" width="100px" height="100px"></a>
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' with no arguments not found. 1 pattern(s) tried: ['(?P<page_num>\\d+)/$']
ERROR 2020-04-14 12:41:43,460 basehttp 124 "GET /login/ HTTP/1.1" 500 135497
INFO 2020-04-14 12:44:36,492 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
INFO 2020-04-14 12:44:36,525 basehttp 124 "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2020-04-14 12:44:36,532 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 304 0
INFO 2020-04-14 12:44:36,545 basehttp 124 "GET /static/js/login.js HTTP/1.1" 304 0
WARNING 2020-04-14 12:44:36,571 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-14 12:44:42,373 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-14 12:44:42,428 basehttp 124 "GET / HTTP/1.1" 200 2771
INFO 2020-04-14 12:44:42,442 basehttp 124 "GET /static/js/index.js HTTP/1.1" 304 0
ERROR 2020-04-16 00:32:43,616 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-16 00:32:43,794 basehttp 124 "GET / HTTP/1.1" 500 98313
INFO 2020-04-16 00:34:44,663 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
INFO 2020-04-16 00:34:44,686 basehttp 124 "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2020-04-16 00:34:44,691 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 304 0
INFO 2020-04-16 00:34:44,694 basehttp 124 "GET /static/js/login.js HTTP/1.1" 304 0
WARNING 2020-04-16 00:34:45,182 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-16 00:34:51,357 basehttp 124 "POST /login/ HTTP/1.1" 302 0
ERROR 2020-04-16 00:34:51,383 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'tb_backup_info.db_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 37, in get
    for backup in backups:
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'tb_backup_info.db_id' in 'field list'")
ERROR 2020-04-16 00:34:51,864 basehttp 124 "GET / HTTP/1.1" 500 216241
INFO 2020-04-16 00:38:24,423 basehttp 124 "GET /register/ HTTP/1.1" 200 3436
INFO 2020-04-16 00:38:24,444 basehttp 124 "GET /static/js/register.js HTTP/1.1" 200 5114
WARNING 2020-04-16 00:38:25,778 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-16 00:38:25,783 basehttp 124 "GET /image_codes/417c172e-7bb3-4d66-a6c4-c50a6dd46cb8/ HTTP/1.1" 200 3461
INFO 2020-04-16 00:38:36,417 basehttp 124 "GET /usernames/wuyang/count HTTP/1.1" 200 41
WARNING 2020-04-16 00:38:57,160 base 152 Not Found: /check_image_codes/uwr7&uuid=417c172e-7bb3-4d66-a6c4-c50a6dd46cb8
WARNING 2020-04-16 00:38:57,163 basehttp 124 "GET /check_image_codes/uwr7&uuid=417c172e-7bb3-4d66-a6c4-c50a6dd46cb8 HTTP/1.1" 404 4469
INFO 2020-04-16 00:38:57,173 basehttp 124 "GET /usernames/wuyang/count HTTP/1.1" 200 41
INFO 2020-04-16 00:38:57,252 basehttp 124 "POST /register/ HTTP/1.1" 302 0
INFO 2020-04-16 00:38:57,318 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-16 00:38:57,355 basehttp 124 "GET /static/js/index.js HTTP/1.1" 304 0
WARNING 2020-04-16 00:39:17,543 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:39:29,977 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-16 00:39:30,131 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:42:27,829 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-16 00:42:30,204 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-16 00:42:36,305 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-16 00:42:36,801 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-16 00:42:44,015 basehttp 124 "POST /login/ HTTP/1.1" 302 0
ERROR 2020-04-16 00:42:44,064 exception 135 Internal Server Error: /databases/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 77, in get
    return render(request, 'user_center_site.html', context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/template/backends/jinja2.py", line 81, in render
    return self.template.render(context)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/templates/user_center_site.html", line 43, in top-level template code
    <li><a href="{{ url('users:address') }}" class="active">· 数据库信息</a></li>
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'address' not found. 'address' is not a valid view function or pattern name.
ERROR 2020-04-16 00:42:44,376 basehttp 124 "GET /databases/ HTTP/1.1" 500 142567
INFO 2020-04-16 00:44:12,190 basehttp 124 "GET /databases/ HTTP/1.1" 200 5458
INFO 2020-04-16 00:44:12,221 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 7948
WARNING 2020-04-16 00:44:12,257 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 00:44:15,712 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:44:36,597 basehttp 124 "GET /databases/ HTTP/1.1" 200 5458
WARNING 2020-04-16 00:44:36,746 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:45:36,487 basehttp 124 "GET /databases/ HTTP/1.1" 200 5458
WARNING 2020-04-16 00:45:36,602 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:45:46,262 basehttp 124 "GET /databases/ HTTP/1.1" 200 5458
WARNING 2020-04-16 00:45:46,373 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:46:36,739 basehttp 124 "GET /databases/ HTTP/1.1" 200 5445
INFO 2020-04-16 00:46:36,754 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
INFO 2020-04-16 00:46:37,943 basehttp 124 "GET /databases/ HTTP/1.1" 200 5445
WARNING 2020-04-16 00:46:40,358 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:47:04,231 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-16 00:47:04,261 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
INFO 2020-04-16 00:47:04,290 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-16 00:47:04,291 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-16 00:47:04,312 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-16 00:47:04,314 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-16 00:47:04,321 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-16 00:47:04,336 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-16 00:47:04,338 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
WARNING 2020-04-16 00:47:04,399 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-16 00:47:04,413 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-16 00:47:17,011 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
INFO 2020-04-16 00:47:17,031 basehttp 124 "GET /databases/ HTTP/1.1" 200 5445
INFO 2020-04-16 00:47:17,055 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 7948
WARNING 2020-04-16 00:47:17,100 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 00:47:17,111 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:49:34,533 basehttp 124 "GET /databases/ HTTP/1.1" 200 5445
INFO 2020-04-16 00:49:34,563 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-16 00:49:34,599 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 00:49:34,664 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:53:24,262 basehttp 124 "GET /databases/ HTTP/1.1" 200 5558
INFO 2020-04-16 00:53:24,298 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-16 00:53:24,396 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:57:13,815 basehttp 124 "GET /databases/ HTTP/1.1" 200 5594
INFO 2020-04-16 00:57:13,858 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-16 00:57:13,919 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:58:08,366 basehttp 124 "GET /databases/ HTTP/1.1" 200 5594
WARNING 2020-04-16 00:58:08,414 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 00:58:08,448 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 00:58:15,430 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-16 00:58:15,454 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
INFO 2020-04-16 00:58:15,479 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-16 00:58:15,492 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-16 00:58:15,496 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-16 00:58:15,510 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-16 00:58:15,517 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-16 00:58:15,522 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-16 00:58:15,548 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
WARNING 2020-04-16 00:58:15,581 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-16 00:58:15,585 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-16 00:58:22,516 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
WARNING 2020-04-16 01:01:53,827 csrf 160 Forbidden (CSRF token missing or incorrect.): /databases/
WARNING 2020-04-16 01:01:53,834 basehttp 124 "POST /databases/ HTTP/1.1" 403 2502
WARNING 2020-04-16 01:01:55,988 csrf 160 Forbidden (CSRF token missing or incorrect.): /databases/
WARNING 2020-04-16 01:01:55,992 basehttp 124 "POST /databases/ HTTP/1.1" 403 2502
INFO 2020-04-16 01:02:01,051 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-16 01:02:01,178 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
WARNING 2020-04-16 01:02:01,191 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 01:02:07,820 basehttp 124 "POST /login/ HTTP/1.1" 302 0
WARNING 2020-04-16 01:11:04,865 csrf 160 Forbidden (CSRF token missing or incorrect.): /databases/
WARNING 2020-04-16 01:11:04,869 basehttp 124 "POST /databases/ HTTP/1.1" 403 2502
INFO 2020-04-16 01:11:08,568 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-16 01:11:08,629 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
WARNING 2020-04-16 01:11:08,665 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 01:11:19,353 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-16 01:11:36,436 basehttp 124 "GET /databases/ HTTP/1.1" 200 5594
INFO 2020-04-16 01:11:36,461 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 7948
WARNING 2020-04-16 01:11:36,491 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 01:11:36,501 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 01:13:04,890 basehttp 124 "GET /databases/ HTTP/1.1" 200 5594
WARNING 2020-04-16 01:13:04,945 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 01:13:05,016 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 01:14:39,452 basehttp 124 "GET /databases/ HTTP/1.1" 200 5592
WARNING 2020-04-16 01:14:39,577 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-16 01:16:43,920 basehttp 124 "GET /databases/ HTTP/1.1" 200 5592
INFO 2020-04-16 01:16:43,954 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 8014
WARNING 2020-04-16 01:16:44,017 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-16 01:16:44,036 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 00:39:53,650 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-17 00:39:53,692 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
INFO 2020-04-17 00:39:53,740 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 304 0
INFO 2020-04-17 00:39:53,744 basehttp 124 "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2020-04-17 00:39:53,784 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 304 0
INFO 2020-04-17 00:39:53,785 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 304 0
INFO 2020-04-17 00:39:53,794 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 304 0
INFO 2020-04-17 00:39:53,803 basehttp 124 "GET /static/js/common.js HTTP/1.1" 304 0
INFO 2020-04-17 00:39:53,820 basehttp 124 "GET /static/js/login.js HTTP/1.1" 304 0
WARNING 2020-04-17 00:39:53,924 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-17 00:39:53,933 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-17 00:40:04,398 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
INFO 2020-04-17 00:40:07,729 basehttp 124 "GET /databases/ HTTP/1.1" 200 5592
INFO 2020-04-17 00:40:07,755 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-17 00:40:07,802 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 01:05:05,056 basehttp 124 "GET /databases/ HTTP/1.1" 200 5592
WARNING 2020-04-17 01:05:05,181 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 01:05:18,532 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-17 01:05:18,554 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
INFO 2020-04-17 01:05:18,587 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-17 01:05:18,598 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-17 01:05:18,616 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-17 01:05:18,617 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-17 01:05:18,621 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-17 01:05:18,643 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
INFO 2020-04-17 01:05:18,661 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
WARNING 2020-04-17 01:05:18,713 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
WARNING 2020-04-17 01:05:18,748 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 01:05:25,974 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
INFO 2020-04-17 01:05:27,831 basehttp 124 "GET /databases/ HTTP/1.1" 200 5592
INFO 2020-04-17 01:05:27,870 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 8050
WARNING 2020-04-17 01:05:27,920 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-17 01:05:27,944 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 01:07:35,090 basehttp 124 "GET /databases/ HTTP/1.1" 200 5592
INFO 2020-04-17 01:07:35,113 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-17 01:07:35,160 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 01:09:26,762 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
INFO 2020-04-17 01:09:26,787 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-17 01:09:26,841 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-17 01:09:26,859 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-17 01:09:26,881 basehttp 124 "GET /static/images/edit.png HTTP/1.1" 404 1658
INFO 2020-04-17 13:45:49,815 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-17 13:45:49,852 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-17 13:45:49,904 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 304 0
INFO 2020-04-17 13:45:49,907 basehttp 124 "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2020-04-17 13:45:49,910 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 304 0
INFO 2020-04-17 13:45:49,914 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 304 0
INFO 2020-04-17 13:45:49,918 basehttp 124 "GET /static/js/common.js HTTP/1.1" 304 0
INFO 2020-04-17 13:45:49,924 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 304 0
INFO 2020-04-17 13:45:49,929 basehttp 124 "GET /static/js/login.js HTTP/1.1" 304 0
WARNING 2020-04-17 13:45:49,970 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 404 1667
INFO 2020-04-17 13:45:56,580 basehttp 124 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2020-04-17 13:45:56,632 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-17 13:45:56,649 basehttp 124 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2020-04-17 13:45:56,656 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
INFO 2020-04-17 13:46:06,917 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
INFO 2020-04-17 13:46:06,929 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-17 13:46:06,965 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 404 1667
WARNING 2020-04-17 13:46:06,980 basehttp 124 "GET /static/images/edit.png HTTP/1.1" 404 1658
WARNING 2020-04-17 13:46:27,245 base 152 Not Found: /databases/user_center_order.html
WARNING 2020-04-17 13:46:27,247 basehttp 124 "GET /databases/user_center_order.html HTTP/1.1" 404 4359
INFO 2020-04-17 13:46:36,814 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
WARNING 2020-04-17 13:47:29,134 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:47:43,219 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
WARNING 2020-04-17 13:47:43,318 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:48:33,626 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
WARNING 2020-04-17 13:48:33,997 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:49:26,025 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
WARNING 2020-04-17 13:49:26,105 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:49:42,687 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:49:42,710 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
INFO 2020-04-17 13:49:42,737 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-17 13:49:42,758 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-17 13:49:42,758 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-17 13:49:42,786 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-17 13:49:42,793 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-17 13:49:42,796 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-17 13:49:42,799 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
INFO 2020-04-17 13:49:42,841 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
WARNING 2020-04-17 13:49:42,869 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:49:50,211 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:49:52,022 basehttp 124 "GET /databases/ HTTP/1.1" 200 5596
INFO 2020-04-17 13:49:52,061 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 8050
INFO 2020-04-17 13:49:52,095 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
WARNING 2020-04-17 13:49:52,158 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:49:52,185 basehttp 124 "GET /static/images/edit.png HTTP/1.1" 200 1244
ERROR 2020-04-17 13:50:03,320 exception 135 Internal Server Error: /databases/1/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'databas_id'
ERROR 2020-04-17 13:50:03,460 basehttp 124 "DELETE /databases/1/ HTTP/1.1" 500 86629
ERROR 2020-04-17 13:50:13,687 exception 135 Internal Server Error: /databases/1/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'databas_id'
ERROR 2020-04-17 13:50:13,818 basehttp 124 "DELETE /databases/1/ HTTP/1.1" 500 86629
ERROR 2020-04-17 13:50:14,440 exception 135 Internal Server Error: /databases/1/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'databas_id'
ERROR 2020-04-17 13:50:14,567 basehttp 124 "DELETE /databases/1/ HTTP/1.1" 500 86629
INFO 2020-04-17 13:53:33,141 basehttp 124 "DELETE /databases/1/ HTTP/1.1" 200 81
INFO 2020-04-17 13:53:39,186 basehttp 124 "GET /databases/ HTTP/1.1" 200 5483
WARNING 2020-04-17 13:53:39,350 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:53:58,663 basehttp 124 "POST /databases/create/ HTTP/1.1" 200 174
INFO 2020-04-17 13:54:08,231 basehttp 124 "PUT /databases/2/title/ HTTP/1.1" 200 63
INFO 2020-04-17 13:55:53,182 basehttp 124 "GET /logout/ HTTP/1.1" 302 0
INFO 2020-04-17 13:55:53,190 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:55:53,212 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
WARNING 2020-04-17 13:55:53,309 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:55:59,933 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:56:07,488 basehttp 124 "GET /databases/ HTTP/1.1" 200 5593
WARNING 2020-04-17 13:56:07,582 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:56:09,000 basehttp 124 "GET /logout/ HTTP/1.1" 302 0
INFO 2020-04-17 13:56:09,010 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:56:09,020 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
WARNING 2020-04-17 13:56:09,114 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-17 13:56:16,057 base 152 Not Found: /login/databases
WARNING 2020-04-17 13:56:16,059 basehttp 124 "GET /login/databases HTTP/1.1" 404 4309
INFO 2020-04-17 13:56:20,174 basehttp 124 "GET /databases HTTP/1.1" 301 0
INFO 2020-04-17 13:56:20,184 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:56:20,195 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
WARNING 2020-04-17 13:56:20,290 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:56:25,793 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 302 0
INFO 2020-04-17 13:56:25,818 basehttp 124 "GET /databases/ HTTP/1.1" 200 5593
WARNING 2020-04-17 13:56:25,897 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:58:01,201 basehttp 124 "GET /databases/ HTTP/1.1" 200 5578
WARNING 2020-04-17 13:58:01,265 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:58:05,551 basehttp 124 "GET /databases/ HTTP/1.1" 200 5578
WARNING 2020-04-17 13:58:05,609 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:58:19,420 basehttp 124 "GET /databases/ HTTP/1.1" 200 5584
WARNING 2020-04-17 13:58:19,503 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:58:59,179 basehttp 124 "GET /databases/ HTTP/1.1" 200 5578
WARNING 2020-04-17 13:58:59,244 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 13:59:31,156 basehttp 124 "GET /databases/ HTTP/1.1" 200 5436
WARNING 2020-04-17 13:59:31,228 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 14:00:14,547 basehttp 124 "GET /databases/ HTTP/1.1" 200 5419
WARNING 2020-04-17 14:00:14,645 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 14:05:11,284 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-17 14:05:11,307 basehttp 124 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2020-04-17 14:05:11,317 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
WARNING 2020-04-17 14:05:11,390 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-17 14:05:13,458 basehttp 124 "GET /backup/ HTTP/1.1" 200 3180
INFO 2020-04-17 14:05:13,489 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 2518
INFO 2020-04-17 14:05:13,499 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
WARNING 2020-04-17 14:05:13,528 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
ERROR 2020-04-17 14:05:44,576 exception 135 Internal Server Error: /backup/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 273, in post
    filename=res1)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'dbpassword' is an invalid keyword argument for this function
ERROR 2020-04-17 14:05:44,763 basehttp 124 "POST /backup/ HTTP/1.1" 500 110416
ERROR 2020-04-20 13:21:07,203 exception 135 Internal Server Error: /backup/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 228, in post
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-20 13:21:07,375 basehttp 124 "POST /backup/ HTTP/1.1" 500 99883
ERROR 2020-04-20 13:21:10,298 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-20 13:21:10,457 basehttp 124 "GET / HTTP/1.1" 500 98186
INFO 2020-04-20 13:21:23,037 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
INFO 2020-04-20 13:21:23,067 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 304 0
INFO 2020-04-20 13:21:23,070 basehttp 124 "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2020-04-20 13:21:23,082 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 304 0
INFO 2020-04-20 13:21:23,087 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 304 0
INFO 2020-04-20 13:21:23,101 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 304 0
INFO 2020-04-20 13:21:23,111 basehttp 124 "GET /static/js/common.js HTTP/1.1" 304 0
INFO 2020-04-20 13:21:23,126 basehttp 124 "GET /static/js/login.js HTTP/1.1" 304 0
WARNING 2020-04-20 13:21:23,179 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:21:29,365 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-20 13:21:29,409 basehttp 124 "GET /databases/ HTTP/1.1" 200 5561
INFO 2020-04-20 13:21:29,442 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-20 13:21:29,505 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:21:57,655 basehttp 124 "POST /databases/create/ HTTP/1.1" 200 179
INFO 2020-04-20 13:22:04,988 basehttp 124 "PUT /databases/3/title/ HTTP/1.1" 200 63
INFO 2020-04-20 13:22:18,177 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
WARNING 2020-04-20 13:22:18,266 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:22:20,348 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
WARNING 2020-04-20 13:22:20,420 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:22:21,570 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
WARNING 2020-04-20 13:22:21,638 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:22:22,670 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
WARNING 2020-04-20 13:22:22,741 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:22:23,532 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
WARNING 2020-04-20 13:22:23,604 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:22:24,816 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
WARNING 2020-04-20 13:22:24,875 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 13:25:08,686 basehttp 124 "GET /backup/ HTTP/1.1" 200 3180
INFO 2020-04-20 13:25:08,702 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 304 0
INFO 2020-04-20 13:25:08,720 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 304 0
WARNING 2020-04-20 13:25:08,760 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 13:44:23,167 base 152 Not Found: /addresses/
WARNING 2020-04-20 13:44:23,169 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4294
INFO 2020-04-20 13:44:32,126 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-20 13:44:32,156 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-20 13:44:38,301 basehttp 124 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2020-04-20 13:44:38,354 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-20 13:44:47,523 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-20 13:44:52,628 basehttp 124 "GET /backup/ HTTP/1.1" 200 2828
WARNING 2020-04-20 13:44:56,537 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:19:46,141 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
WARNING 2020-04-20 14:19:46,228 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:20:49,864 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
WARNING 2020-04-20 14:20:49,933 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:21:39,246 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-20 14:21:40,866 basehttp 124 "GET /userdatabases HTTP/1.1" 301 0
INFO 2020-04-20 14:21:51,607 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 14:24:19,657 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
WARNING 2020-04-20 14:24:19,798 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:24:39,131 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
WARNING 2020-04-20 14:24:39,244 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:26:52,634 basehttp 124 "GET /backup/ HTTP/1.1" 302 0
INFO 2020-04-20 14:26:52,656 basehttp 124 "GET /login/?next=/backup/ HTTP/1.1" 200 2346
INFO 2020-04-20 14:26:52,683 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-20 14:26:52,686 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-20 14:26:52,708 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-20 14:26:52,709 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-20 14:26:52,725 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-20 14:26:52,735 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-20 14:26:52,777 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
INFO 2020-04-20 14:26:52,782 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
WARNING 2020-04-20 14:26:52,811 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:26:59,313 basehttp 124 "POST /login/?next=/backup/ HTTP/1.1" 302 0
INFO 2020-04-20 14:26:59,337 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
INFO 2020-04-20 14:26:59,363 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 3392
INFO 2020-04-20 14:26:59,403 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
WARNING 2020-04-20 14:26:59,429 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:27:10,800 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 14:27:31,634 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
WARNING 2020-04-20 14:27:31,764 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:27:33,993 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 14:28:15,975 basehttp 124 "GET /backup/ HTTP/1.1" 302 0
INFO 2020-04-20 14:28:15,988 basehttp 124 "GET /login/?next=/backup/ HTTP/1.1" 200 2346
INFO 2020-04-20 14:28:16,016 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-20 14:28:16,030 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-20 14:28:16,036 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-20 14:28:16,038 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-20 14:28:16,039 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-20 14:28:16,048 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-20 14:28:16,061 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
INFO 2020-04-20 14:28:16,114 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
WARNING 2020-04-20 14:28:16,131 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:28:25,108 basehttp 124 "POST /login/?next=/backup/ HTTP/1.1" 302 0
INFO 2020-04-20 14:28:25,130 basehttp 124 "GET /backup/ HTTP/1.1" 200 2418
INFO 2020-04-20 14:28:25,151 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 3389
WARNING 2020-04-20 14:28:25,222 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:28:25,254 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2020-04-20 14:28:27,061 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
WARNING 2020-04-20 14:28:32,018 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:28:34,050 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:30:26,359 basehttp 124 "GET /backup/ HTTP/1.1" 200 2421
INFO 2020-04-20 14:30:26,384 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 304 0
WARNING 2020-04-20 14:30:26,427 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:30:28,230 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
WARNING 2020-04-20 14:30:30,300 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:30:31,550 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:30:37,416 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:30:45,509 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:30:46,935 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:30:52,982 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:30:59,492 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:32:22,947 basehttp 124 "GET /backup/ HTTP/1.1" 200 2421
INFO 2020-04-20 14:32:22,976 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 304 0
WARNING 2020-04-20 14:32:23,078 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:32:26,644 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
WARNING 2020-04-20 14:32:29,134 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:32:56,047 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:35:31,549 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:35:31,564 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:35:38,903 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:35:52,063 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:35:56,700 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:46:20,366 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:46:25,385 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:48:03,818 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:48:07,468 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:56:01,389 basehttp 124 "POST /backup/ HTTP/1.1" 403 18
WARNING 2020-04-20 14:56:03,278 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:59:03,211 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-20 14:59:48,112 csrf 160 Forbidden (CSRF cookie not set.): /backup/
WARNING 2020-04-20 14:59:48,119 basehttp 124 "POST /backup/ HTTP/1.1" 403 2857
WARNING 2020-04-20 14:59:50,006 csrf 160 Forbidden (CSRF cookie not set.): /backup/
WARNING 2020-04-20 14:59:50,010 basehttp 124 "POST /backup/ HTTP/1.1" 403 2857
INFO 2020-04-20 14:59:52,212 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-20 14:59:52,253 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-20 14:59:52,309 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-20 14:59:52,321 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-20 14:59:52,325 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-20 14:59:52,337 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-20 14:59:52,373 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-20 14:59:52,394 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-20 14:59:52,429 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
WARNING 2020-04-20 14:59:52,440 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 14:59:52,481 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2020-04-20 14:59:58,776 basehttp 124 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2020-04-20 14:59:58,845 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-20 14:59:58,873 basehttp 124 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2020-04-20 14:59:58,878 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
WARNING 2020-04-20 14:59:59,003 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:00:06,422 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
INFO 2020-04-20 15:00:06,469 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 3389
INFO 2020-04-20 15:00:06,481 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
WARNING 2020-04-20 15:00:06,527 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:00:21,647 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:00:28,782 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
WARNING 2020-04-20 15:00:28,958 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:00:55,576 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-20 15:00:55,610 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 8050
INFO 2020-04-20 15:00:55,656 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
WARNING 2020-04-20 15:00:55,682 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:00:55,718 basehttp 124 "GET /static/images/edit.png HTTP/1.1" 200 1244
INFO 2020-04-20 15:01:01,491 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
WARNING 2020-04-20 15:01:01,595 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:01:33,631 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
WARNING 2020-04-20 15:01:33,721 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:01:46,342 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
INFO 2020-04-20 15:01:54,547 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:01:54,576 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:01:57,194 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
INFO 2020-04-20 15:01:57,241 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:02:00,884 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
INFO 2020-04-20 15:02:00,928 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:02:06,322 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-20 15:02:08,658 basehttp 124 "GET /backup/ HTTP/1.1" 200 2443
INFO 2020-04-20 15:02:08,708 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:02:12,155 basehttp 124 "GET /incre/ HTTP/1.1" 200 3444
INFO 2020-04-20 15:02:12,173 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 200 2951
INFO 2020-04-20 15:02:30,911 basehttp 124 "GET /incre/ HTTP/1.1" 200 3444
INFO 2020-04-20 15:02:38,763 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:02:38,816 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:02:41,846 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:02:41,900 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:02:57,718 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-20 15:02:57,748 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-20 15:02:57,760 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-20 15:02:57,772 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-20 15:02:57,777 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-20 15:02:57,781 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-20 15:02:57,783 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
INFO 2020-04-20 15:02:57,784 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-20 15:02:57,787 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-20 15:02:58,362 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2020-04-20 15:02:58,375 basehttp 124 "GET /login/?next=/ HTTP/1.1" 200 2346
INFO 2020-04-20 15:02:58,452 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2020-04-20 15:03:04,474 basehttp 124 "POST /login/?next=/ HTTP/1.1" 302 0
INFO 2020-04-20 15:03:04,498 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-20 15:03:04,526 basehttp 124 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2020-04-20 15:03:04,528 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
INFO 2020-04-20 15:03:06,099 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:06,113 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 3389
INFO 2020-04-20 15:03:06,124 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2020-04-20 15:03:06,161 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:30,949 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:31,004 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:31,791 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:31,832 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:32,411 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:32,452 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:32,597 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:32,644 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:32,751 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:32,799 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:32,911 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:32,958 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:33,064 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:33,106 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:33,233 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:33,278 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 15:03:33,386 basehttp 124 "GET /backup/ HTTP/1.1" 200 2423
INFO 2020-04-20 15:03:33,427 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
WARNING 2020-04-20 15:04:21,981 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:05:12,631 basehttp 124 "GET /backup/ HTTP/1.1" 302 0
INFO 2020-04-20 15:05:12,685 basehttp 124 "GET /login/?next=/backup/ HTTP/1.1" 200 2346
INFO 2020-04-20 15:05:12,717 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-20 15:05:12,742 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-20 15:05:12,749 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-20 15:05:12,753 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-20 15:05:12,790 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-20 15:05:12,798 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-20 15:05:12,818 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
WARNING 2020-04-20 15:05:12,874 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:05:12,889 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2020-04-20 15:05:20,492 basehttp 124 "POST /login/?next=/backup/ HTTP/1.1" 302 0
INFO 2020-04-20 15:05:20,559 basehttp 124 "GET /backup/ HTTP/1.1" 200 2397
INFO 2020-04-20 15:05:20,591 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 3389
INFO 2020-04-20 15:05:20,631 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
WARNING 2020-04-20 15:05:20,651 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-20 15:05:20,710 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
ERROR 2020-04-20 23:52:35,470 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-20 23:52:35,654 basehttp 124 "GET / HTTP/1.1" 500 98313
INFO 2020-04-20 23:52:40,644 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
INFO 2020-04-20 23:52:47,195 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-20 23:52:47,236 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-20 23:52:47,256 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 8050
INFO 2020-04-20 23:52:47,262 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
INFO 2020-04-20 23:52:47,298 basehttp 124 "GET /static/images/edit.png HTTP/1.1" 200 1244
INFO 2020-04-20 23:52:52,990 basehttp 124 "GET /backup/ HTTP/1.1" 200 2417
INFO 2020-04-20 23:52:53,016 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 304 0
INFO 2020-04-20 23:52:53,063 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-20 23:57:36,594 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
INFO 2020-04-20 23:57:42,037 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-20 23:57:42,079 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-20 23:57:51,051 basehttp 124 "GET /backup/ HTTP/1.1" 200 2411
INFO 2020-04-20 23:57:51,121 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:01:03,427 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-21 00:01:03,466 basehttp 124 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2020-04-21 00:01:03,467 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
INFO 2020-04-21 00:01:05,153 basehttp 124 "GET /backup/ HTTP/1.1" 200 2411
INFO 2020-04-21 00:01:05,237 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:02:20,021 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-21 00:02:21,267 basehttp 124 "GET /backup/ HTTP/1.1" 200 2411
INFO 2020-04-21 00:02:21,338 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:04:15,520 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-21 00:04:16,740 basehttp 124 "GET /backup/ HTTP/1.1" 200 2411
INFO 2020-04-21 00:04:16,797 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:07:37,620 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-21 00:07:38,841 basehttp 124 "GET /incre/ HTTP/1.1" 200 2369
INFO 2020-04-21 00:07:38,855 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 200 2951
INFO 2020-04-21 00:09:28,097 basehttp 124 "GET /incre/ HTTP/1.1" 200 2369
INFO 2020-04-21 00:09:31,806 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:09:31,869 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
ERROR 2020-04-21 00:09:52,858 exception 135 Internal Server Error: /backup/
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 279, in post
    filename=res1)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'dbuser' is an invalid keyword argument for this function
ERROR 2020-04-21 00:09:53,040 basehttp 124 "POST /backup/ HTTP/1.1" 500 110372
INFO 2020-04-21 00:12:05,495 basehttp 124 "GET / HTTP/1.1" 200 1741
INFO 2020-04-21 00:12:06,690 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:12:06,755 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:12:41,716 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-21 00:12:52,993 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:12:53,607 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:12:57,886 basehttp 124 "POST /backup/ HTTP/1.1" 200 2401
INFO 2020-04-21 00:13:26,955 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-21 00:13:36,661 basehttp 124 "PUT /databases/3/ HTTP/1.1" 200 198
INFO 2020-04-21 00:13:44,708 basehttp 124 "PUT /databases/3/ HTTP/1.1" 200 198
INFO 2020-04-21 00:13:56,190 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:13:56,243 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:14:03,819 basehttp 124 "POST /backup/ HTTP/1.1" 200 2401
INFO 2020-04-21 00:14:03,873 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 299
INFO 2020-04-21 00:17:20,997 basehttp 124 "GET /databases/ HTTP/1.1" 200 5678
INFO 2020-04-21 00:17:31,164 basehttp 124 "PUT /databases/3/ HTTP/1.1" 200 195
INFO 2020-04-21 00:17:35,414 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:17:35,646 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 296
INFO 2020-04-21 00:17:46,614 basehttp 124 "POST /backup/ HTTP/1.1" 200 2401
INFO 2020-04-21 00:17:46,661 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 296
INFO 2020-04-21 00:21:31,905 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:21:31,992 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:34:21,850 basehttp 124 "GET / HTTP/1.1" 200 5331
INFO 2020-04-21 00:34:26,033 basehttp 124 "GET /incre/ HTTP/1.1" 200 2621
WARNING 2020-04-21 00:34:33,489 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
ERROR 2020-04-21 00:34:49,506 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-21 00:34:49,674 basehttp 124 "GET / HTTP/1.1" 500 97721
INFO 2020-04-21 00:34:53,332 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
INFO 2020-04-21 00:34:53,360 basehttp 124 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2020-04-21 00:34:53,374 basehttp 124 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2020-04-21 00:34:53,377 basehttp 124 "GET /static/css/main.css HTTP/1.1" 200 40094
INFO 2020-04-21 00:34:53,393 basehttp 124 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2020-04-21 00:34:53,424 basehttp 124 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2020-04-21 00:34:53,432 basehttp 124 "GET /static/images/logo.jpg HTTP/1.1" 200 15735
INFO 2020-04-21 00:34:53,441 basehttp 124 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2020-04-21 00:34:53,464 basehttp 124 "GET /static/js/login.js HTTP/1.1" 200 1106
WARNING 2020-04-21 00:34:53,469 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:34:58,796 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-21 00:34:58,844 basehttp 124 "GET /databases/ HTTP/1.1" 200 5675
INFO 2020-04-21 00:34:58,878 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 200 8050
INFO 2020-04-21 00:34:58,945 basehttp 124 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
WARNING 2020-04-21 00:34:58,964 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:34:59,025 basehttp 124 "GET /static/images/edit.png HTTP/1.1" 200 1244
INFO 2020-04-21 00:35:02,788 basehttp 124 "GET / HTTP/1.1" 200 5331
INFO 2020-04-21 00:35:02,814 basehttp 124 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2020-04-21 00:35:02,839 basehttp 124 "GET /static/js/index.js HTTP/1.1" 200 129
WARNING 2020-04-21 00:35:02,888 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:35:04,078 basehttp 124 "GET /incre/ HTTP/1.1" 200 2621
INFO 2020-04-21 00:35:04,108 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 200 2418
INFO 2020-04-21 00:35:04,144 basehttp 124 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
WARNING 2020-04-21 00:35:04,175 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:35:04,261 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:35:04,262 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 257
INFO 2020-04-21 00:37:39,847 basehttp 124 "GET /incre/ HTTP/1.1" 200 2626
INFO 2020-04-21 00:37:39,872 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 200 2418
WARNING 2020-04-21 00:37:39,949 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:37:39,976 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:37:39,993 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 257
INFO 2020-04-21 00:38:26,981 basehttp 124 "GET /incre/ HTTP/1.1" 200 2652
INFO 2020-04-21 00:38:27,015 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 304 0
WARNING 2020-04-21 00:38:27,094 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:38:27,129 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 257
INFO 2020-04-21 00:38:27,132 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:38:36,815 basehttp 124 "GET /incre/ HTTP/1.1" 200 2656
INFO 2020-04-21 00:38:36,843 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 304 0
WARNING 2020-04-21 00:38:36,875 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:38:36,951 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:38:36,969 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 257
WARNING 2020-04-21 00:38:49,312 basehttp 124 "POST /incre/ HTTP/1.1" 403 18
WARNING 2020-04-21 00:38:50,909 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:43:21,869 basehttp 124 "GET /incre/ HTTP/1.1" 200 2656
INFO 2020-04-21 00:43:21,897 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 304 0
WARNING 2020-04-21 00:43:21,949 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:43:22,008 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 257
INFO 2020-04-21 00:43:22,011 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:43:46,278 basehttp 124 "POST /incre/ HTTP/1.1" 200 2722
WARNING 2020-04-21 00:43:46,331 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:43:46,389 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 294
INFO 2020-04-21 00:43:46,401 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:44:04,392 basehttp 124 "GET /databases/ HTTP/1.1" 200 5675
WARNING 2020-04-21 00:44:04,456 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:34,272 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-21 00:47:34,360 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:40,111 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-21 00:47:40,156 basehttp 124 "GET /databases/ HTTP/1.1" 200 5662
WARNING 2020-04-21 00:47:40,230 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:42,067 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 00:47:42,089 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 200 1708
WARNING 2020-04-21 00:47:42,137 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:42,177 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
WARNING 2020-04-21 00:47:43,790 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:45,777 basehttp 124 "GET /incre/ HTTP/1.1" 200 2656
INFO 2020-04-21 00:47:45,796 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 304 0
WARNING 2020-04-21 00:47:45,872 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:45,895 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:47:45,905 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 294
WARNING 2020-04-21 00:47:47,695 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:48,740 basehttp 124 "GET /databases/ HTTP/1.1" 200 5662
WARNING 2020-04-21 00:47:48,792 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:47:50,138 basehttp 124 "GET / HTTP/1.1" 200 6049
WARNING 2020-04-21 00:47:50,216 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-21 00:47:53,777 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:04,693 basehttp 124 "GET / HTTP/1.1" 200 6049
WARNING 2020-04-21 00:48:04,766 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-21 00:48:06,231 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:07,189 basehttp 124 "GET /databases/ HTTP/1.1" 200 5662
WARNING 2020-04-21 00:48:07,246 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:08,856 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
WARNING 2020-04-21 00:48:08,916 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:08,968 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
WARNING 2020-04-21 00:48:10,366 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:11,053 basehttp 124 "GET /incre/ HTTP/1.1" 200 2656
WARNING 2020-04-21 00:48:11,112 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:11,200 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 112
INFO 2020-04-21 00:48:11,204 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 294
WARNING 2020-04-21 00:48:12,517 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 00:48:29,051 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-21 00:48:29,128 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 01:01:10,228 basehttp 124 "GET /register/ HTTP/1.1" 200 3436
INFO 2020-04-21 01:01:10,241 basehttp 124 "GET /static/js/register.js HTTP/1.1" 200 5114
WARNING 2020-04-21 01:01:10,305 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 01:01:10,336 basehttp 124 "GET /image_codes/40e20369-7047-4f7d-bcd7-ebcbcd6238f5/ HTTP/1.1" 200 3294
INFO 2020-04-21 01:01:15,831 basehttp 124 "GET /usernames/wanghao/count HTTP/1.1" 200 41
INFO 2020-04-21 01:01:24,048 basehttp 124 "GET /usernames/chenhao/count HTTP/1.1" 200 41
INFO 2020-04-21 01:01:30,887 basehttp 124 "GET /image_codes/1fba8ff1-7d05-4c84-8a8b-a9b363039db4/ HTTP/1.1" 200 3892
WARNING 2020-04-21 01:01:36,692 base 152 Not Found: /check_image_codes/rw4m&uuid=1fba8ff1-7d05-4c84-8a8b-a9b363039db4
WARNING 2020-04-21 01:01:36,695 basehttp 124 "GET /check_image_codes/rw4m&uuid=1fba8ff1-7d05-4c84-8a8b-a9b363039db4 HTTP/1.1" 404 4796
INFO 2020-04-21 01:01:36,707 basehttp 124 "GET /usernames/chenhao/count HTTP/1.1" 200 41
INFO 2020-04-21 01:01:36,782 basehttp 124 "POST /register/ HTTP/1.1" 302 0
INFO 2020-04-21 01:01:36,806 basehttp 124 "GET /databases/ HTTP/1.1" 200 5438
WARNING 2020-04-21 01:01:36,869 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 01:12:13,036 basehttp 124 "GET /databases/ HTTP/1.1" 200 5438
WARNING 2020-04-21 01:12:13,090 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:26:19,701 basehttp 124 "GET /databases/ HTTP/1.1" 200 5438
INFO 2020-04-21 12:26:19,744 basehttp 124 "GET /static/js/user_center_site.js HTTP/1.1" 304 0
WARNING 2020-04-21 12:26:19,789 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:26:37,097 basehttp 124 "POST /databases/create/ HTTP/1.1" 200 176
INFO 2020-04-21 12:26:42,773 basehttp 124 "PUT /databases/4/title/ HTTP/1.1" 200 63
ERROR 2020-04-21 12:26:49,236 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-21 12:26:49,407 basehttp 124 "GET / HTTP/1.1" 500 98368
ERROR 2020-04-21 12:26:55,722 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-21 12:26:55,890 basehttp 124 "GET / HTTP/1.1" 500 98504
ERROR 2020-04-21 12:26:58,171 exception 135 Internal Server Error: /
Traceback (most recent call last):
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wuyang/Desktop/Django_project/xtra/Xtra/Xtra/apps/contents/views.py", line 34, in get
    user = User.objects.get(username=username)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wuyang/.virtualenvs/Django_v1/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
users.models.DoesNotExist: User matching query does not exist.
ERROR 2020-04-21 12:26:58,330 basehttp 124 "GET / HTTP/1.1" 500 98344
INFO 2020-04-21 12:27:03,537 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-21 12:27:03,615 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:09,354 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-21 12:27:09,377 basehttp 124 "GET /databases/ HTTP/1.1" 200 5662
WARNING 2020-04-21 12:27:09,441 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:13,184 basehttp 124 "GET / HTTP/1.1" 200 6049
WARNING 2020-04-21 12:27:13,240 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:17,364 basehttp 124 "GET /logout/ HTTP/1.1" 302 0
INFO 2020-04-21 12:27:17,371 basehttp 124 "GET /databases/ HTTP/1.1" 302 0
INFO 2020-04-21 12:27:17,382 basehttp 124 "GET /login/?next=/databases/ HTTP/1.1" 200 2346
WARNING 2020-04-21 12:27:17,441 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:25,208 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 200 2467
WARNING 2020-04-21 12:27:25,291 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:31,616 basehttp 124 "POST /login/?next=/databases/ HTTP/1.1" 200 2467
WARNING 2020-04-21 12:27:31,693 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:35,573 basehttp 124 "GET /register/ HTTP/1.1" 200 3436
WARNING 2020-04-21 12:27:35,623 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:35,692 basehttp 124 "GET /image_codes/3e6a3dde-5f66-4468-a295-1e7515c22862/ HTTP/1.1" 200 3304
INFO 2020-04-21 12:27:42,746 basehttp 124 "GET /usernames/chenhao/count HTTP/1.1" 200 41
INFO 2020-04-21 12:27:42,824 basehttp 124 "GET /login/ HTTP/1.1" 200 2346
WARNING 2020-04-21 12:27:42,895 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:51,017 basehttp 124 "POST /login/ HTTP/1.1" 302 0
INFO 2020-04-21 12:27:51,039 basehttp 124 "GET /databases/ HTTP/1.1" 200 5550
WARNING 2020-04-21 12:27:51,095 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:52,851 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:27:52,950 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:54,552 basehttp 124 "GET /incre/ HTTP/1.1" 200 2656
INFO 2020-04-21 12:27:54,569 basehttp 124 "GET /static/js/Incre.js HTTP/1.1" 304 0
WARNING 2020-04-21 12:27:54,639 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:54,664 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 74
INFO 2020-04-21 12:27:54,674 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
WARNING 2020-04-21 12:27:58,934 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:59,616 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
INFO 2020-04-21 12:27:59,638 basehttp 124 "GET /static/js/backup.js HTTP/1.1" 304 0
WARNING 2020-04-21 12:27:59,673 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:27:59,708 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
WARNING 2020-04-21 12:28:02,148 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:03,791 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:28:03,843 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:07,286 basehttp 124 "GET /databases/ HTTP/1.1" 200 5550
WARNING 2020-04-21 12:28:07,341 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:15,988 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:28:16,069 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-21 12:28:22,114 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:23,245 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
WARNING 2020-04-21 12:28:23,297 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:23,338 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
WARNING 2020-04-21 12:28:24,813 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:26,486 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
WARNING 2020-04-21 12:28:26,527 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:26,574 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
WARNING 2020-04-21 12:28:28,205 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:29,075 basehttp 124 "GET /incre/ HTTP/1.1" 200 2656
WARNING 2020-04-21 12:28:29,133 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:29,199 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
INFO 2020-04-21 12:28:29,201 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 74
WARNING 2020-04-21 12:28:30,820 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:57,333 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:28:57,419 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:28:58,838 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:28:58,890 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-21 12:29:01,910 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:29:02,929 basehttp 124 "GET /backup/ HTTP/1.1" 200 2341
WARNING 2020-04-21 12:29:03,063 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:29:03,080 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
INFO 2020-04-21 12:29:06,605 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:29:06,689 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-21 12:29:12,461 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
WARNING 2020-04-21 12:29:13,042 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:31:46,656 basehttp 124 "GET / HTTP/1.1" 200 1741
WARNING 2020-04-21 12:31:46,713 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:32:50,704 basehttp 124 "GET / HTTP/1.1" 200 1751
WARNING 2020-04-21 12:32:50,766 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:32:51,748 basehttp 124 "GET /databases/ HTTP/1.1" 200 5550
WARNING 2020-04-21 12:32:51,795 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:32:55,172 basehttp 124 "GET /backup/ HTTP/1.1" 200 2351
WARNING 2020-04-21 12:32:55,230 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:32:55,275 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
INFO 2020-04-21 12:32:55,869 basehttp 124 "GET /databases/ HTTP/1.1" 200 5550
WARNING 2020-04-21 12:32:55,920 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:32:57,216 basehttp 124 "GET /incre/ HTTP/1.1" 200 2666
WARNING 2020-04-21 12:32:57,270 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
INFO 2020-04-21 12:32:57,333 basehttp 124 "GET /userbackups/ HTTP/1.1" 200 74
INFO 2020-04-21 12:32:57,348 basehttp 124 "GET /userdatabases/ HTTP/1.1" 200 91
INFO 2020-04-21 12:32:57,760 basehttp 124 "GET /databases/ HTTP/1.1" 200 5550
WARNING 2020-04-21 12:32:57,819 basehttp 124 "GET /static/js/axios.min.map HTTP/1.1" 404 1661
